domain_name = "upwardmobility.online"
cognito_domain_name = "auth.upwardmobility.online"
bucket_name = "upwardmobilitywebsite"
game_bucket = "upwardmobilitybuild"
error_page = "404.html"
index_page = "index.html"
region = "us-east-2"
